### ISSUE TITLE
Do not hardcode API url in `api/client/client.go`

### ISSUE THREAD

**Issue by rogerthebest** [sniptt-official/ots#6]
Ideally, this would be configurable, I assume should be possible via ENV var and/or flag during build.

Might also make sense to make this configurable by the user, however that would be a separate issue.

**Comment by rickymarcon** [comment]
I believe https://github.com/sniptt-official/ots/commit/192e81cdb8866be1a1f436094e809d19f0c5e4e1 closes this now.
